#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define TIME_INTERVAL  10


#define SINGLE_BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!//
#define SINGLE_DEADBAND_WHEEL(x) ((abs(x) >= 10)? x: 0)

void left_base(int joy_x)
{
	 float k=1;
	 int drivePower;

   joy_x = k*joy_x;
   drivePower = SINGLE_DEADBAND_WHEEL(joy_x);

   motor[motorLeft] = SINGLE_BOUND_WHEEL(drivePower);
}
void right_base (int joy_y)
{
	 float k=1;
	 int drivePower;

   joy_y = k*joy_y;
   drivePower = SINGLE_DEADBAND_WHEEL(joy_y);

   motor[motorRight] = SINGLE_BOUND_WHEEL(drivePower);
}


task main()
{
	//initializeRobot();
	while(true)
	{
		getJoystickSettings(joystick);
		left_base(joystick.joy1_y1);
		right_base(joystick.joy1_y2);
		wait1Msec(TIME_INTERVAL);
	}

}
