#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define TIME_INTERVAL  10


#define SINGLE_BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!//
#define SINGLE_DEADBAND_WHEEL(x) ((abs(x) >= 10)? x: 0)

void drive_regular(int joy_x, int joy_y)
{
	 float k=1;
	 int drivePower, turnPower;

   joy_x = k*joy_x;
   joy_y = k*joy_y;

   drivePower = SINGLE_DEADBAND_WHEEL(joy_x);
   turnPower = SINGLE_DEADBAND_WHEEL(joy_y);

   motor[motorLeft] = SINGLE_BOUND_WHEEL(drivePower + turnPower);
   motor[motorRight] = SINGLE_BOUND_WHEEL(drivePower - turnPower);

   motor[motorLeft] = SINGLE_BOUND_WHEEL(drivePower);
}

void drive_slow(int joy_a, int joy_b)
{
	 float k=.5;
	 int drivePower, turnPower;

   joy_a = k*joy_a;
   joy_b = k*joy_b;

   drivePower = SINGLE_DEADBAND_WHEEL(joy_a);
   turnPower = SINGLE_DEADBAND_WHEEL(joy_b);

   motor[motorLeft] = SINGLE_BOUND_WHEEL(drivePower + turnPower);
   motor[motorRight] = SINGLE_BOUND_WHEEL(drivePower - turnPower);

   motor[motorLeft] = SINGLE_BOUND_WHEEL(drivePower);
}


task main()
{
	//initializeRobot();
	while(true)
	{
		getJoystickSettings(joystick);
		drive_regular(joystick.joy1_x1, joystick.joy1_y1);
		drive_slow(joystick.joy1_x2, joystick.joy1_y2);
		wait1Msec(TIME_INTERVAL);
	}

}
