#pragma config(Sensor, S1,     ,               sensorTouch)
#pragma config(Sensor, S2,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


task main(){
	while(true){
		motor[motorA] = joystick.joy1_y1;
		motor[motorB] = joystick.joy1_y1;
		motor[motorA] = joystick.joy1_x1;
		motor[motorB] = -joystick.joy1_x1;
	}
}
