#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C2_1,     motorIntake,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     motorLeftWs,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     motorRightWs,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_2,    servoHook,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_1,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void intake ()
{
	motor[motorIntake] = 100;
}

void arm (int z)
{
	motor[motorArm] = ((z*100)/128);
}

int deadband(int x)
{
	if (x < 10 && x > -10)
		return 0;
	else
		return x;
}

void drive (int x ,int y)
{
	x = deadband(x);
	y = deadband(y);
	int leftDrive = ((x*100)/128)+((y*100)/128);
	int rightDrive = ((y*100)/128)-((x*100)/128);
	motor[motorLeftWs] = -1 * rightDrive;
	motor[motorRightWs] = -1 * leftDrive;
}

task main()
{

	while(true)
	{
		getJoystickSettings(joystick);

		if (joy1Btn(4)==1)
		{
			servo[servoHook] = 240;
			writeDebugStreamLine("hook down");
		}
		else if (joy1Btn(3)==1)
		{
			servo[servoHook] = 10;
			writeDebugStreamLine("hook up");
		}
		if (joy1Btn(2)==1)
		{
			if (abs(joystick.joy1_y2)>10)
				motor[motorIntake]=0;
			else
				intake();
		}
		else
			motor[motorIntake]=0;

		if (abs(joystick.joy1_x2)>10)
		{
			if ((joystick.joy1_x2)>10)
			{
				arm(joystick.joy1_x2);
				motor[motorIntake] = 40;
			}
			else if ((joystick.joy1_x2)<-10)
			{
				arm(joystick.joy1_x2);
				motor[motorIntake] = -40;
			}
		}
		else
			motor[motorArm] = 0;

		drive(-1*joystick.joy1_y1, joystick.joy1_x1);

		//motor[motorArm] = joystick.joy1_x1;





	}
}
//there is a problem with the driving part, lagging and then nonstop driving after. MUST FIX!!
