#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C2_1,     motorIntake,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     motorLeftWs,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     motorRightWs,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    servoHook,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void hookDown ()
{
	servo[servoHook] = 255;
}
void hookUp ()
{
	servo[servoHook] = 19;
}

void intake ()
{
	motor[motorIntake] = 100;
}

void arm (int z)
{
	motor[motorArm] = ((z*10)/128);
}

void drive (int x ,int y)
{
	int leftDrive = ((x*100)/128)+((y*100)/128);
	int rightDrive = ((y*100)/128)-((x*100)/128);
	motor[motorLeftWs] = -1 * rightDrive;
	motor[motorRightWs] = -1 * leftDrive;
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);

		if (joy1Btn(4)==1)
			hookDown();
		if (joy1Btn(3)==1)
			hookUp();

		if (joy1Btn(2)==1)
		{
			if (abs(joystick.joy1_y2)>10)
				motor[motorIntake]=0;
			else
				intake();
		}
		else
			motor[motorIntake]=0;

		if (abs(joystick.joy1_x2)>10)
		{
			if ((joystick.joy1_x2)>0)
			{
				arm(joystick.joy1_x2);
				motor[motorIntake] = 40;
			}
			else if ((joystick.joy1_x2)<0)
			{
				arm(joystick.joy1_x2);
				motor[motorIntake] = -40;
			}
		}
		else
			motor[motorArm] = 0;

		drive(-1*joystick.joy1_y1, joystick.joy1_x1);
		arm(joystick.joy1_x2);

		//motor[motorArm] = joystick.joy1_x1;

		writeDebugStreamLine("joystick x is: %d", joystick.joy1_y2);



	}
}
