#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FrontR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     FrontL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RearR,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     RearL,         tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADBAND_THRESHOLD 10
#define BOUND(x) (((x) < -100)? -100: ((x) > 100)? 100: (x))
#define DEADBAND(x) ((abs(x) >= DEADBAND_THRESHOLD)? x: 0) //if the value is kinda close to 0, just read it as 0


#include "JoystickDriver.c"

void baseMove(int joy1x1, int joy1y1, int joy1x2, int joy1y2){
	int turn = DEADBAND(joy1x2);
	int forward = DEADBAND(joy1y2);
	int LeftDG = -DEADBAND(joy1x1);
	int RightDG = DEADBAND(joy1y1); //Processes the numbers
	motor[FrontR] = BOUND(forward - turn + LeftDG); //runs the motors at a readable value
	motor[FrontL] = BOUND(forward + turn + RightDG);
	motor[RearR] = BOUND(forward - turn + RightDG);
	motor[RearL] = BOUND(forward + turn + LeftDG);
}

task main()
{
	while(true){
		baseMove(joystick.joy1_x1, joystick.joy1_y1, joystick.joy1_x2, joystick.joy1_y2);
	}

}
