#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S4,     ultrasonic,     sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Brush,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     LLinear,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     Shooter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     RLinear,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    LTalon,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    BRHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    FLHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    BLHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    FRHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_1,    RTalon,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{

}

int deadband(int x)
{
	if (x <= 10 && x >= -10)
		x = 0;
	return x;
}

int motorScale(float x)
{
	x = ((x / 128) * 100);
	if (x > 100)
		x = 100;
	return x;
}

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = 1.0;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = -k 	* motorScale(x);
	yPower = -k 	* motorScale(y);
	rPower = kR	* motorScale(r);

	FLPower = motorScale(		xPower	+	yPower	+	rPower);
	BLPower = motorScale( -	xPower 	+	yPower	+	rPower);
	BRPower = motorScale(		xPower	+	yPower	-	rPower);
	FRPower = motorScale( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}

void dropTalons ()
{
	int RTalon = 53;	// smaller value is more down
	int LTalon = 248 - RTalon;

	servo[LTalon] = LTalon;
	servo[RTalon] = RTalon;
}

void liftTalons ()
{
	int RTalon = 250;  // greater value is more up
	int LTalon = 244 - RTalon;

	servo[LTalon] = LTalon;
	servo[RTalon] = RTalon;
}

task main()
{
	//initializeRobot();
	waitForStart();
	drive(0, 100, 0);		// drive forward off ramp
	liftTalons();			// talons up
	wait1Msec(2950);
	dropTalons();			// talons down
	wait1Msec(450);
	drive(-50, -35, 75);	// spin around goal
	wait1Msec(1250);
	drive(75, 20, 75);		// spin even harder
	wait1Msec(1200);
	drive(50, 100, 40);		// spin less drive more
	wait1Msec(3000);
	drive(0, 100, 0);		// drive those last couple feet
	wait1Msec(650);
}
