#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     LightA,         sensorLightActive)
#pragma config(Sensor, S3,     Ultra,          sensorSONAR)
#pragma config(Sensor, S4,     LightB,         sensorLightActive)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    leftTalon,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rightTalon,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//const float x = .7;

void intakeButton (int a)
{
	if (a ==	1)
		motor[intake]=100;
	else
		motor[intake]=0;
}

int deadband (int b) //deadband (writeDebugStreamLine)
{
	if (b >= -5 && b <= 5)
	{
		b=0;
	}
	return b;
}


float motorScale (int c)
{
	int d;
	d = (float)(100*c)/128;
	return d;
}


void motorDrive (int x, int y)
	{
		x = motorScale(x);
		y = motorScale(y);
		motor[leftDrive]	= y + x;
		motor[rightDrive]	= y - x;
	}

void talons (int a, int b)
	{
	if (a== 1)
	{
		servo[rightTalon] = 215;
		servo[leftTalon] = 45;
	}
	else if (b== 1)
	{
		servo[rightTalon] = 90;
		servo[leftTalon] = 180;
	}
	}


void initializeRobot()
{
	talons(0, 1);
}



task main()
{
  initializeRobot();
 waitForStart();

//use ultra to find the box
//if not the box, use second light sensor to follow
//drive to the other side

 	while (SensorValue(LightA) <= 60 ) //write code for going from back wall to stopping line thingy
  		motorDrive(-90,-90);

 	while (SensorValue(LightB) < 60)
	{
		if(SensorValue(LightA) > 60)
		{
			motor[leftDrive] = -25;
			motor[rightDrive] = 0;
		}
		else if(SensorValue(LightA) <= 60)
		{
			motor[leftDrive] = 0;
			motor[rightDrive] = -25;
		}
	}

	if (SensorValue[LightB] > 60)
  	{
  		if (SensorValue[Ultra] <= 43.5 )
  		{
  			motorDrive (0,-128);
  			while (SensorValue[Ultra] > 0 )
  		}
	}

  	else if (SensorValue[Ultra] >= 43.5)
  	{
		if(SensorValue(LightA) > 60)
		{
			motor[leftDrive] = -25;
			motor[rightDrive] = 0;
		}

		else if(SensorValue(LightA) <= 60)
		{
			motor[leftDrive] = 0;
			motor[rightDrive] = -25;
		}
	}

	}

  		intakeButton(1);
  		wait1Msec(2000);
  		motorDrive(0,100);
  		wait1Msec(3000);

  /*
  	motorDrive(0,-128);
 	wait1Msec(2000*x); //2000 with 4 v battery
 	motorDrive(128,0);
 	wait1Msec(1350*x); //1350 with 4 v battery
 	motorDrive(0,-128);
 	wait1Msec(1200*x); //1000
 	motorDrive(-128,0);
  	wait1Msec(1200*x); //1230
  	motorDrive(0,-128);
  	wait1Msec(2600*x); //3500
  	motorDrive(0,0);
  	wait10Msec(0*x);
  	talons(1,0);
  	wait1Msec(1000*x); //1000
  	intakeButton(1);
  	wait1Msec(2000*x);

  	if (SensorValue[ultra] <= && => )
  	{
  		motorDrive(0,-128);
  		wait1Msec();

	}
  	else if (SensorValue[ultra] => )
  	{
  		motorDrive(-128,0);
  		wait1Msec();
  		motorDrive(0,-128);
  		wait1Msec();
  		motorDrive(128,0);
  		wait1Msec();
  		motorDrive(0,-128);
  		wait1Msec();
	}


  		intakeButton(1);
  		wait1Msec(2000);
  		motorDrive(0,100);
  		wait1Msec();
*/

}
