#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     LightA,         sensorLightActive)
#pragma config(Sensor, S3,     Ultra,          sensorSONAR)
#pragma config(Sensor, S4,     LightB,         sensorLightActive)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    leftTalon,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rightTalon,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//const float x = .7;

void intakeButton (int a)
{
	if (a ==	1)
		motor[intake]=100;
	else
		motor[intake]=0;
}

int deadband (int b) //deadband (writeDebugStreamLine)
{
	if (b >= -5 && b <= 5)
	{
		b=0;
	}
	return b;
}


float motorScale (int c)
{
	int d;
	d = (float)(100*c)/128;
	return d;
}


void motorDrive (int x, int y)
	{
		x = motorScale(x);
		y = motorScale(y);
		motor[leftDrive]	= y + x;
		motor[rightDrive]	= y - x;
	}

void talons (int a, int b)
	{
	if (a== 1)
	{
		servo[rightTalon] = 205;
		servo[leftTalon] = 45;
	}
	else if (b== 1)
	{
		servo[rightTalon] = 90;
		servo[leftTalon] = 180;
	}
	}


void initializeRobot()
{
	talons(0, 1);
}



task main()
{
	initializeRobot();
	waitForStart();


														//robot travels diagonally to first line
  	//	motorDrive(-100,-110);
	//PlayTone(500,    7);

	motorDrive(0,-128);
	wait1Msec(1800);
	motorDrive(-100,80);
	wait1Msec(500);
	while (SensorValue(LightA)<= 50)
		motorDrive(0,40);

	/*while (SensorValue(LightA) <= 50)
	{
		motor[leftDrive] = -25;
		motor[rightDrive] = 0;
	}*/
	while (SensorValue(LightB) < 50)
	{
		if(SensorValue(LightA) > 50)
		{
			motor[leftDrive] = -25;
			motor[rightDrive] = 0;
		}
		else if(SensorValue(LightA) <= 50)
		{
			motor[leftDrive] = 0;
			motor[rightDrive] = -25;
		}
	}
	//PlayTone(  0,    0);
													//robot will follow white line until stopping point
													//robot senses stopping point
 	if (SensorValue(Ultra) <= 30 )				//if robot senses the box, enter clamping mode
	{
		writeDebugStreamLine("IT WORKED");
		motor[leftDrive] = 0;
		motor[rightDrive] = -10;
		wait1Msec(150);
		motorDrive(0,-128);
		wait1Msec(1000);
		motorDrive(0,0);
		talons(1,0);
		intakeButton(1);
		wait1Msec(2000);
		motorDrive(0,128);
		wait1Msec(3500);								//hopefully this is talons down
	}
	else if (SensorValue(Ultra) >= 30)				//if robot does not sense the box, turn until lightA senses second line
	{
		if(SensorValue(LightA) > 60)
			motorDrive(-128,0);
		else if(SensorValue(LightA) < 60)
			motorDrive(-128,0);
	}

		while (SensorValue(LightB) < 60)				//robot follows line until second stopping point (stops when lightB senses line)
		{
			if(SensorValue(LightA) > 60)
			{
				motor[leftDrive] = -25;
				motor[rightDrive] = 0;
			}
			else if(SensorValue(LightA) <= 60)
			{
				motor[leftDrive] = 0;
				motor[rightDrive] = -25;
			}
		}
			if(SensorValue(LightB) > 60)				//doubt this is right
				motorDrive(-128,0);
			else if(SensorValue(LightB) <= 60)
				motorDrive(-128,0);

			while (SensorValue(Ultra) <= 43.5)
				motorDrive(128,0); 						//turn ultra so it is right at the edge of the box?

			motorDrive(0,-128);
			wait1Msec(1500);
			motorDrive(0,0);
			talons(1,0);										//robot senses box and repositions itself to allow bot to clamp down on box
			intakeButton(1);
			wait1Msec(2000);
			motorDrive(0,128);
			wait1Msec(3500);
}
