#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    leftTalon,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    rightTalon,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void intakeButton (int a, int b)
{
	if (a == 1)
		motor[intake] = 100;
	else if (b == 1)
		motor[intake] = -100;
	else
		motor[intake] = 0;
}


int deadband (int b) //deadband (writeDebugStreamLine)
{
	if (b >= -5 && b <= 5)
	{
		b=0;
	}
	return b;
}


float motorScale (int c)
{
	int d;
	d = (float)(100*c)/128;
	return d;
}


void motorDrive (int x, int y)
	{
		x = motorScale(x);
		y = motorScale(y);
		motor[leftDrive]	= y + x;
		motor[rightDrive]	= y - x;
	}

void talons (int a, int b)
	{
	if (a== 1)
	{
		servo[rightTalon] = 215;
		servo[leftTalon] = 45;
	}
	else if (b== 1)
	{
		servo[rightTalon] = 90;
		servo[leftTalon] = 180;
	}
	}

task main()
{
	while (true)
	{
			getJoystickSettings(joystick);

			intakeButton(joy1Btn(1), joy1Btn(3));

			motorDrive(deadband(joystick.joy1_x1),deadband(joystick.joy1_y1));

			talons(joy1Btn(5), joy1Btn(6));

	}



}
