#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bigBall,        sensorI2CMuxController)
#pragma config(Sensor, S3,     smallBall,      sensorNone)
#pragma config(Sensor, S4,     ultrasonic,     sensorNone)
#pragma config(Motor,  mtr_S1_C2_1,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     LLinear,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     Shooter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     RLinear,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{

}

int deadband(int x)
{
	if (x <= 10 && x >= -10)
		x = 0;
	return x;
}

int motorScale(float x)
{
	x = ((x / 128) * 100);
	if (x > 100)
		x = 100;
	return x;
}

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = 1.0;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = k 	* motorScale(x);
	yPower = k 	* motorScale(y);
	rPower = kR	* motorScale(r);

	FLPower = motorScale(		xPower	+	yPower	+	rPower);
	BLPower = motorScale( -	xPower 	+	yPower	+	rPower);
	BRPower = motorScale(		xPower	+	yPower	-	rPower);
	FRPower = motorScale( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}

void dropTalons ()
{
	int hookUpRight = 31;	// smaller value is more down
	int hookUp = 248 - hookUpRight;

	servo[leftHook] = hookUp;
	servo[rightHook] = hookUpRight;
}

void liftTalons ()
{
	int HookDownRight = 250; // greater value is more up
	int HookDown = 244 - HookDownRight;

	servo[leftHook] = HookDown;
	servo[rightHook] = HookDownRight;
}

bool checkDistance() // Check to see if robot is facing center goal.
{
	// TODO add ultrasonic code to check if goal is in position
}

void openBallGate()
{
	
}

void closeBallGate()
{
	
}

void setHoodHeight()
{
	
}

void centerRobotGoal()
{
	
}

task main()
{
	waitForStart();   // wait for start of autonomous phase
	//initializeRobot();

	drive(0, 100, 0); // drive forward
	wait1ms(250);
	drive(0, 0, 0); // stop robot
	if (checkDistance()) // check if goal is in first position
	{
		centerRobotGoal(); // *OPTIONAL* make sure robot is centered with the goal
		setHoodHeight(120); // move hood to 120 mark (center goal height)
		openBallGate(); // Release balls
	}
	else
	{
		drive(100, 0, 50); // Drive in Circle
		wait1ms(250);
		drive(0, 0, 0) // stop robot
		
		if (checkDistance()) // check if goal is in second position
		{
			centerRobotGoal(); // *OPTIONAL* make sure robot is centered with the goal
			setHoodHeight(120); // move hood to 120 mark (center goal height)
			openBallGate(); // Release balls
		}
		else
		{
			drive(100, 0, 50); // Drive in Circle
			wait1ms(250);
			drive(0, 0, 0) // stop robot
			
			if (checkDistance()) // check if goal is in third position
			{
				centerRobotGoal(); // *OPTIONAL* make sure robot is centered with the goal
				setHoodHeight(120); // move hood to 120 mark (center goal height)
				openBallGate(); // Release balls
			}
		}
	}
	
}