#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     bigBall,        sensorLightActive)
#pragma config(Sensor, S3,     smallBall,      sensorLightActive)
#pragma config(Sensor, S4,     ultrasonic,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     shooterMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     armMotor,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bigGate,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    rightRamp,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    leftRamp,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    smallGate,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define DEADBAND(x) ((abs(x) >= 10)? x: 0)

int motorScale(float x)
{
	x = ((x / 128) * 100);
	if (x > 100)
		x = 100;
	return x;
}

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = 1.0;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = k 	* motorScale(DEADBAND(x));
	yPower = k 	* motorScale(DEADBAND(y));
	rPower = kR	* motorScale(DEADBAND(r));

	FLPower = motorScale(		xPower	+	yPower	+	rPower);
	BLPower = motorScale( -	xPower 	+	yPower	+	rPower);
	BRPower = motorScale(		xPower	+	yPower	-	rPower);
	FRPower = motorScale( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}


task main()
{
	waitForStart();
	drive(0, - 100, 0);
	wait1Msec(3000);
	drive(0, 0, 0);
}
