#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     winchMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    leftFoot,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    rightFoot,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftProng,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    rightProng,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Class Constants
#define GYRO_OFFSET 0

// Class Variables
float heading;
//float forward_heading;

float motorScale(float x)
{
	x = ((x / 128) * 100);
	if (x > 100)
		x = 100;
	return x;
}

long readGyro()
{
	return SensorValue(gyro)-GYRO_OFFSET;
}

void resetGyro()
{
	heading = 90;
}

void initRobot()
{
	resetGyro();
}

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = 1.0;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = k 	* motorScale(x);
	yPower = k 	* motorScale(y);
	rPower = kR	* motorScale(r);

	FLPower = motorScale(		xPower	+	yPower	+	rPower);
	BLPower = motorScale( -	xPower 	+	yPower	+	rPower);
	BRPower = motorScale(		xPower	+	yPower	-	rPower);
	FRPower = motorScale( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}

void updateHeading()
{

}

void getHeading()
{

}

void adjustedDrive(float x, float y, float r)
{
	//x = motorScale(x);
	//y = motorScale(y);
	//r = motorScale(z);

	float desired_heading = atan(y/x)*180/PI;
	float power = sqrt((x*x)+(y*y));

	float new_heading = 90 + (desired_heading-heading); // check this

	int newX = power*cosDegrees(newHeading);
	int newY = power*sinDegrees(newHeading);
	drive(newX, newY, r);
}

task main()
{
	while (true)
	{
		wait1Msec(2);
		updateHeading();
		getJoystickSettings();
		adjustedDrive(deadband(joystick.joy1_x1), deadband(joystick.joy1_y1, deadband(joystick.joy1_x2)));


	}
}
