#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FLWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FRWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BLWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     BRWheel,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

// Constants
#define FORWARD	1
#define RIGHT		2
#define BACK		3
#define LEFT		4

#define ROTATE_LEFT		1
#define ROTATE_RIGHT	2

#define FULL_MOTOR_POWER 90

task main() {
	while (true) {
		getJoystickSettings(joystick);

	}
}

void holoDrive(int joy1_x, int joy1_y, int joy2_x, int joy2_y) {
	// Joystick input must be within {-100 - 100}

}

/*
void simpleHoloDrive(int movement, int rotation) {
	// Movement input must be: {1, 2, 3, 4} corresponding to {forward, right, back, left}
	// Rotation input must be: {1, 2} corresponding to {rotateLeft, rotateRight}
}
*/

void simpleHoloMove(int movement) {
	// Movement input must be: {1, 2, 3, 4} corresponding to {forward, right, back, left}
	switch (movement) {
		case FORWARD:
			motor[FLWheel] = 1*FULL_MOTOR_POWER;
			motor[FRWheel] = 1*FULL_MOTOR_POWER;
			motor[BLWheel] = 1*FULL_MOTOR_POWER;
			motor[BRWheel] = 1*FULL_MOTOR_POWER;
			break;
		case RIGHT:
			motor[FLWheel] = 1*FULL_MOTOR_POWER;
			motor[FRWheel] = -1*FULL_MOTOR_POWER;
			motor[BLWheel] = -1*FULL_MOTOR_POWER;
			motor[BRWheel] = 1*FULL_MOTOR_POWER;
			break;
		case BACK:
			motor[FLWheel] = -1*FULL_MOTOR_POWER;
			motor[FRWheel] = -1*FULL_MOTOR_POWER;
			motor[BLWheel] = -1*FULL_MOTOR_POWER;
			motor[BRWheel] = -1*FULL_MOTOR_POWER;
			break;
		case LEFT:
			motor[FLWheel] = -1*FULL_MOTOR_POWER;
			motor[FRWheel] = 1*FULL_MOTOR_POWER;
			motor[BLWheel] = 1*FULL_MOTOR_POWER;
			motor[BRWheel] = -1*FULL_MOTOR_POWER;
			break;
	}
}

void simpleHoloRotate(int rotation) {
	// Rotation input must be: {1, 2} corresponding to {rotateLeft, rotateRight}

}
