#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     shooterMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define DEADBAND(x) ((abs(x) >= 10)? x: 0)
#define SCALE_INPUT(x) (((x) / 128) * 100)

int powerFraction(int x) {
	return ((x/200)*100);
}

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = .8;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = k 	* SCALE_INPUT(DEADBAND(x));
	yPower = k 	* SCALE_INPUT(DEADBAND(y));
	rPower = kR	* SCALE_INPUT(DEADBAND(r));

	if ((xPower + rPower) > 100) {

	}
	FLPower = scalePower(	xPower	+	yPower	+	rPower);
	BLPower = scalePower( -	xPower 	+	yPower	+	rPower);
	BRPower = scalePower(	xPower	+	yPower	-	rPower);
	FRPower = scalePower( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
		drive(joystick.joy1_x1, joystick.joy1_y1, joystick.joy1_x2); // normal drive
	}
}
