#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     winchMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    footL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    prongL,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    prongR,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    footR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define JOYSTICK_MAX	128
#define MOTOR_MAX		100

int scaleMotorInput(float initVal, float initMax, float finMax)
{
	return ((initVal/initMax)*finMax);
}

int deadband(int x)
{
	if (x <= 5 && x >= -5) {
		x = 0;
	}
	return x;
}

void dropFeet()
{
	servo[footL] = 90; //abritrary
	servo[footR] = 0;
}

void raiseFeet()
{
	servo[footL] = 180;
	servo[footR] = 90;
}

task main()
{
	while (true)
	{
		wait1Msec(5);
		getJoystickSettings(joystick);
		motor[winchMotor] = scaleMotorInput(deadband(joystick.joy1_y1), JOYSTICK_MAX, MOTOR_MAX);
		servo[prongL] = 127+deadband(joystick.joy1_y2);
		servo[prongR] = 127-deadband(joystick.joy1_y2);

		if (joy1Btn(4)) {
			raiseFeet();
		}

		if (joy1Btn(2)) {
			dropFeet();
		}
		//writeDebugStreamLine("%d", scaleMotorInput(deadband(joystick.joy1_y1), JOYSTICK_MAX, MOTOR_MAX));//zaservo[]
	}
}
