#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     shooterMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     armMotor,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bigGate,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    rightRamp,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    leftRamp,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    smallGate,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-sensormux.h"
#include "lego-light.h"
#include "hitechnic-gyro.h"
#include "hitechnic-irseeker-v2.h"
#include "lego-ultrasound.h"
#include "JoystickDriver.c"
/*
#define bigLightSensor           	  msensor_S2_1
#define	someSensor1          			  msensor_S2_2
#define smallLightSensor      	 		msensor_S2_3
#define someSensor2	          		  msensor_S2_4
//sensor MUX
//Port 1: big ball light (right)
//Port 2:
//Port 3: small ball light (left)
//Port 4:
HTGYROstartCal(gyroSensor);
int gyroRotation = HTGYROreadRot(gyroSensor);
//int distanceInCM = USreadDist(sonarSensor);
int irACDirection = HTIRS2readACDir(irSeekerSensor);
//bool limitSWActive = TSreadState(touchSensor);
*/
/*
#define gyroSensor              msensor_S4_1
#define sonarSensor             msensor_S4_2
#define irSeekerSensor          msensor_S4_3
#define touchSensor             msensor_S4_4ssssss
*/

// Constants
#define DEADBAND(x) ((abs(x) >= 10)? x: 0)
#define WAIT_TIME 5

// Class variables
int bigGateButtonCooldown = 0;
int rampPosition = 128;

int motorScale(float x)
{
	x = ((x / 128) * 100);
	if (x > 100)
		x = 100;
	return x;
}

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = 1.0;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = k 	* motorScale(DEADBAND(x));
	yPower = k 	* motorScale(DEADBAND(y));
	rPower = kR	* motorScale(DEADBAND(r));

	FLPower = motorScale(		xPower	+	yPower	+	rPower);
	BLPower = motorScale( -	xPower 	+	yPower	+	rPower);
	BRPower = motorScale(		xPower	+	yPower	-	rPower);
	FRPower = motorScale( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}

void arm(int x)
{
	float k = .4999999999;
	motor[armMotor] = k * motorScale(x);
}

void shooter(int x)
{
	int k = 100;
	motor[shooterMotor] = x * k;
}

int servo_in = 150;
int servo_in_l = 105;
void ramp_in (int btn_x)
{
	if (btn_x == 1)
	{
		servo[leftRamp] = servo_in;
		servo[leftRamp] = servo_in_l;
	}
}

int servo_middle = 128;
int servo_middle_l = 127;
void ramp_middle (int btn_x)
{
	if (btn_x == 1)
	{
		servo[rightRamp] = servo_middle;
		servo[leftRamp] = servo_middle_l;
	}
}

int servo_out = 150;
int servo_out_l = 105;
void ramp_out (int btn_x)
{
	if (btn_x == 1)
	{
		servo[rightRamp] = servo_out;
		servo[leftHook] = servo_out_l;
	}
}

int hookUpRight = 150;	// smaller value is more up
int hookUp = 250 - hookUpRight;

void servo_up (int btn_x)
{
	if (btn_x == 1)
	{
		servo[leftHook] = hookUp;
		servo[rightHook] = hookUpRight;
	}
}

int HookDownRight = 245; // greater value is more down
int HookDown = 253 - HookDownRight;
void servo_down (int btn_x)
{
	if (btn_x == 1)
	{
		servo[leftHook] = HookDown;
		servo[rightHook] = HookDownRight;
	}
}

void openBigGate ()
{
	if (bigGateButtonCooldown <= 0) {
		servo[bigGate] = 175;
		wait1Msec(260);
		servo[bigGate] = 225;
		bigGateButtonCooldown = 100;
	} else {
		bigGateButtonCooldown--;
	}
}

void openSmallGate ()
{
	if (bigGateButtonCooldown <= 0) {
		servo[smallGate] = 60;
		wait1Msec(150);
		servo[smallGate] = 20;
		bigGateButtonCooldown = 100;
	} else {
		bigGateButtonCooldown--;
	}
}

void moveRampUp (int x)
{
	while (x == 1)
		rampPosition += 2;
	servo[leftRamp] = rampPosition;
	servo[rightRamp] = 256 - rampPosition;
}

void moveRampDown (int x)
{
	while (x == 1)
		rampPosition -= 2;
	servo[leftRamp] = rampPosition;
	servo[rightRamp] = 256 - rampPosition;
}

/*
int big_open = 200;
void open_big (int btn_x)
{
	if (btn_x == 1)
	{
		servo[bigGate] = big_open;
	}
}
int big_close = 120;
void close_big (int btn_x)
{
	if (btn_x == 1)
	{
		servo[bigGate] = big_close;
	}
}
int small_open = 75;
void open_small (int btn_x)
{
	if (btn_x == 1)
	{
		servo[smallGate] = small_open;
	}
}
int small_close = 128;
void close_small (int btn_x)
{
	if (btn_x == 1)
	{
		servo[smallGate] = small_close;
	}
}
*/

task main()
{
	while(true)
	{
		wait1Msec(5);
		getJoystickSettings(joystick);
		drive(joystick.joy1_x1, joystick.joy1_y1, joystick.joy1_x2); // normal drive
		arm(joystick.joy2_y1);
		shooter(joy2Btn(8));
		moveRampUp(joy2Btn(6));
		moveRampDown(joy2btn(5));
		/*
		while (joy1Btn(8)) // cruise control
		{
			arm(0);
			shooter(0);
			wait1Msec(1);
		}
		*/
		/*
		ramp_in(joy1Btn(2));
		ramp_middle(joy1Btn(3));
		ramp_out(joy1Btn(4));
		*/
		servo_up(joy2Btn(4)); //raise hook
		servo_down(joy2Btn(1)); //lower hook
		//writeDebugStreamLine("%d", ServoValue[bigGate]);
		if (joy2Btn(3))
			openBigGate();
		if (joy2Btn(2))
			openSmallGate();
		/*
		open_big(joy1Btn(6));
		close_big(joy1Btn(8));
		open_small(joy1Btn(5));
		close_small(joy1Btn(7));
		*/

		/*
		{
      if(SensorValue(light_big) > 40)  					// If the big ball (right side) Light Sensor reads a value less than 40:
      {
        servo[bigGate] = 200;                  // gate_big (servo) is open
      }
      else                           	    			// If the Light Sensor reads a value greater than or equal to 45:
      {
        servo[smallGate] = 120;                  // gate_big (servo) is closed.
        while(true)
        {
        	if(SensorValue(light_small) > 40)  		// If the small ball (left side) Light Sensor reads a value less than 40:
        	{
        		servo[smallGate] = 200;
        	}
        	else
        	{
        		servo[smallGate] = 120;
        	}
      }
			}
}
*/
}
}
