#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bigBall,        sensorLightActive)
#pragma config(Sensor, S3,     smallBall,      sensorLightActive)
#pragma config(Sensor, S4,     ultrasonic,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     winchMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    leftFoot,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    rightFoot,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    leftProng,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_4,    rightProng,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{

}

int deadband(int x)
{
	if (x <= 10 && x >= -10)
		x = 0;
	return x;
}

int motorScale(float x)
{
	x = ((x / 128) * 100);
	if (x > 100)
		x = 100;
	return x;
}

/*int scaleInput(float initVal, float initMax, float finMax)
{
	return ((initVal/initMax)*finMax);
}*/

void drive(int x, int y, int r)
{
	float k = 1.0;
	float kR = 1.0;

	int xPower, yPower, rPower, FLPower, BLPower, BRPower, FRPower;

	xPower = k 	* motorScale(x);
	yPower = k 	* motorScale(y);
	rPower = kR	* motorScale(r);

	FLPower = motorScale(		xPower	+	yPower	+	rPower);
	BLPower = motorScale( -	xPower 	+	yPower	+	rPower);
	BRPower = motorScale(		xPower	+	yPower	-	rPower);
	FRPower = motorScale( -	xPower	+	yPower	-	rPower);

	motor[FLWheelMotor] = FLPower;
	motor[BLWheelMotor] = BLPower;
	motor[BRWheelMotor] = BRPower;
	motor[FRWheelMotor] = FRPower;
}

void raiseFeet()
{
	int hookUpRight = 100;	// smaller value is more up
	int hookUp = 250 - hookUpRight;

	servo[leftFoot] = hookUp;
	servo[rightFoot] = hookUpRight;
}

void dropFeet()
{
	int HookDownRight = 240; // greater value is more down
	int HookDown = 250 - HookDownRight;

	servo[leftFoot] = HookDown;
	servo[rightFoot] = HookDownRight;
}

void moveProngs(int x)
{
	servo[leftProng] = 127+x;
	servo[rightProng] = 127-x;
}

void moveWinch(int x)
{
	motor[winchMotor] = motorScale(x);
}

task main()
{
	//waitForStart();   // wait for start of tele-op phase
	initializeRobot();
	while (true)
	{
		getJoystickSettings(joystick);

		drive(deadband(joystick.joy1_x1), deadband(joystick.joy1_y1), deadband(joystick.joy1_x2)); // normal drive

		moveWinch(deadband(joystick.joy2_y1));
		moveProngs(deadband(joystick.joy2_y2));

		if (joy2Btn(4))
			raiseFeet();
		if (joy2Btn(1))
			dropFeet();
	}
}
