#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     CMotor,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     AMotor,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    ArmServo,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    ClawServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************PLEASE WORK WITH THESE VALUES**********************************************/

#define rotationCount -1500 													//how much it will rotate, may have to test + and -
#define powerPercentage 50												//how much power to rotate at
#define armServoPower 15													//Power to rotate arm servo at. can be + or -
#define armServoMovementTime 0.5									//Time to move the Servo. Try different values
#define clawServoPosition 	-50								//How far to move the claw servo.


/**************************************MAIN CODE - DO NOT TOUCH*********************************************/

void moveServo(int sec, int power){
	servo[ArmServo] = 117 + power;
	wait1Msec(sec*1000);
	servo[ArmServo] = 117;
}

task main()
{

  nMotorEncoder[AMotor] = 0;  //resets the motor encoder

  nMotorEncoderTarget[AMotor] = -rotationCount; //set the target stopping position

  motor[AMotor] = - powerPercentage; //sets motor to power at powerPercentage

 // moveServo(armServoMovementTime, armServoPower);

 servo[ClawServo] = ServoValue[ClawServo] + clawServoPosition;

  while (nMotorRunState[AMotor] != runStateIdle) //while the encoder wheel turns
  {
    //waits for the motor to stop
  }

  motor[AMotor] = 0; //turns the motor

  wait1Msec(10);
}
