#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     CMotor,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     AMotor,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    ArmServo,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    ClawServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*****************************PLEASE WORK WITH THESE VALUES*************************************************/

#define powerPercentage  10 //the percentage of power it will lift at
#define rotationCount  600 //how much it will rotate


/*************************************MAIN CODE - NEED NOT TOUCH********************************************/

task main()
{

  nMotorEncoder[AMotor] = 0;  //resets the encoder for the Arm Motor

 	while (nMotorEncoder[AMotor] > -rotationCount) //until it has moved rotationCount in either direction
  {
    motor[AMotor] = -powerPercentage; //turn the motor at powerPercentage
  }

  motor[AMotor] = 0; //Once it has reached the rotation count, it will stop

  wait1Msec(1000);

}
