#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     CMotor,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     AMotor,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    ArmServo,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    ClawServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*******************************PLEASE WORK WITH THESE VALUES**********************************************/

#define rotationCount 1440 													//how much it will rotate, may have to test + and -
#define powerPercentage 30												//how much power to rotate at

/**************************************MAIN CODE - DO NOT TOUCH*********************************************/

task main()
{

  nMotorEncoder[AMotor] = 0;  //resets the motor encoder

  nMotorEncoderTarget[AMotor] = -rotationCount; //set the target stopping position

  motor[AMotor] = powerPercentage; //sets motor to power at powerPercentage


  while (nMotorRunState[AMotor] != runStateIdle) //while the encoder wheel turns
  {
    //waits for the motor to stop
  }

  motor[AMotor] = 0; //turns the motor

  wait1Msec(10);
}
