#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     compass,        sensorI2CMuxController)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorC,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorD,        tmotorTetrix, PIDControl, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    armServo1,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    clawServo,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEADBAND_THRESHOLD 10       //*!!Define as 10*//
#define BOUND(x) (((x) > 100)? 100: ((x) < -100)? -100: (x))     //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND(x) ((abs(x) >= DEADBAND_THRESHOLD)? x: 0)     //*!!If the joystick is between -10 and 10, it will be treated as 0 !!*//
#define SERVOBOUND(x) (((x) > 255 )? 255: ((x) < 0)? 0: (x))
#define SERVODEADBAND(x) ( ((abs(x) <= 137) || (abs(x) >= 117))? 127: (x) )

#define TIME_INTERVAL 100
int arm_servo_angle = 0;
int arm_step_angle = 15;
int claw_servo_angle = 0;
int claw_step_angle = 25;

void main_wheel( int joy1_x1, int joy1_y1 )
{
	 int k=8;
   int drivePower = DEADBAND(joy1_x1/k);
   int turnPower  = DEADBAND(joy1_y1/k);

   motor[motorA] = BOUND(drivePower - turnPower);
   motor[motorB] = BOUND(drivePower + turnPower);
}

void central_motor( int joy1_y2 )
{
	int k=8;
	int rotatePower = DEADBAND(joy1_y2/k);
	motor[motorC] = BOUND(rotatePower);
}

void arm_motors( int joy2_y1 )
{
	int k=8;
	int rotatePower = DEADBAND(joy2_y1/k);
	motor[motorD] = BOUND(rotatePower);
}

void arm_servos( int btn1, int btn3 )
{
	if ( btn1 == 1 )
	{
		arm_servo_angle = arm_servo_angle + arm_step_angle;
	} else
	if ( btn3 == 1 )
	{
		arm_servo_angle = arm_servo_angle - arm_step_angle;
	}
	servo[armServo1] = SERVOBOUND(arm_servo_angle); //sets speed to = a value between -127 and 127 + 128

}

void claw_servo ( int btn2, int btn4 )
{
	if ( btn2 == 1 )
	{
		claw_servo_angle = claw_servo_angle + claw_step_angle;
	} else
	if ( btn4 == 1 )
	{
		claw_servo_angle = claw_servo_angle - claw_step_angle;
	}
	servo[clawServo] = SERVOBOUND(claw_servo_angle); //sets speed to = a value between -127 and 127 + 128

}

#include "JoystickDriver.c"
task main()
{
    while(true)
    {
        getJoystickSettings(joystick); // Update Buttons and Joysticks

 				main_wheel( joystick.joy1_x1, joystick.joy1_y1 );
 				central_motor( joystick.joy1_y2 );
 				arm_motors( joystick.joy2_y1 );
        arm_servos( joy2Btn(1), joy2Btn(3) );
        claw_servo( joy2Btn(2), joy2Btn(4) );
 				wait1Msec(TIME_INTERVAL);
    }
}
