#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     color,          sensorLightActive)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRseek,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S3_C1_1,     LeftBase,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     RightBase,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_2,     Elev,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S3_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define FINAL_DISTANCE 30 //*******ADJUST
#define VERTICAL 172
#define SLANTED 230

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"


/******BASE MOVEMENT*******/
void move(int x){
	motor[LeftBase] = x;
	motor[RightBase] = x;
	wait1Msec(50);
}

void stopMotors(){
	motor[LeftBase] = 0;
	motor[RightBase] = 0;
	wait1Msec(50);
}

void moveForward(int sec){
	move(100);
	wait1Msec(sec*1000);
	stopMotors();
	wait1Msec(500);
}

void moveBackward(int sec){
	move(-100);
	wait1Msec(sec*1000);
	stopMotors();
	wait1Msec(100);
}

void pointTurn(float sec, int dir){
		motor[LeftBase] = 100*dir; //+1 is right turn
		motor[RightBase] = -100*dir;
		wait1Msec(sec*1000);
		stopMotors();
		wait1Msec(100);
}

void turnRight(int angle){
	float time = (angle * 0.0091);
		pointTurn(time, 1);
}

void turnLeft(int angle){
	float time = (angle * 0.0091);
	pointTurn(time, -1);
}

void initializeRobot(){
	nMotorEncoder[Elev] = 0;
	turnRight(45);

	/**********RAISE THE ELEVATOR*******/

	/*nMotorEncoder[Elev] = 0; //hopefully zeroes encoder
	nMotorEncoderTarget[Elev] = 500;//Adjust Target
	motor[Elev] = -100;
	while (nMotorRunState[Elev] != runStateIdle){
    // Waits for motors to stop before continuing.
  }
  motor[Elev] = 0;
	wait1Msec(50);*/

	//Raise the Arm
	motor[Arm] = 50;
	wait1Msec(450); //Time is variable******ADJUST
	motor[Arm] = 20; //Adjust the power to keep it constant
	wait1Msec(50);

	//ADJUST SERVO
	servo[servo1] = VERTICAL;
}

/*******************************MAIN PROGRAM*******************/
task main()
{
	bool hasRing = true;
	int IRZone;
	int val;
	int k = 50; //need to adjust for turning, is turning constant*****ADJUST
	int distance = SensorValue[sonar];

	initializeRobot(); //moves robot into initial position


	while(SensorValue[IRseek] < 1){ //moves until IR finds beacon location
		move(100);
	}
	stopMotors();

	while(hasRing){
		IRZone = SensorValue[IRseek];
		val = IRZone - 5;
		distance = SensorValue[sonar];

		motor[LeftBase] = 50 - (val*k);
		motor[RightBase] = 50 + (val*k);

		if (distance <= FINAL_DISTANCE){
			stopMotors();
			motor[Arm] = 100;
			servo[servo1] = VERTICAL; //MOVES SERVO
			wait1Msec(5000);
			servo[servo1] = SLANTED;
			wait1Msec(400);

			/*//MOVES ELEVATOR DOWN SLIGHTLY
			nMotorEncoderTarget[Elev] = 3000;//Adjust Target
			motor[Elev] = -100;
			while (nMotorRunState[Elev] != runStateIdle){
		    // Waits for motors to stop before continuing.
		  }
		  motor[Elev] = 0;
			wait1Msec(50);*/

			//MOVES OUT OF THE WAY AND LOWERS THE ARM
			motor[Arm] = -25;
			wait1Msec(3750);
			motor[Arm] = 10;
			moveBackward(2);


			/*//MOVE ELEVATOR BACK DOWN TO 0
			nMotorEncoderTarget[Elev] = 100; //Adjust Target
			motor[Elev] = -100;
			while (nMotorRunState[Elev] != runStateIdle){
		    // Waits for motors to stop before continuing.
		  }
		  motor[Elev] = 0;
			wait1Msec(50);*/

			turnRight(180); //Turns 180 degrees
			hasRing = false;
		}

		wait1Msec(50);

	}

}
