#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     rightbase,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     elevator,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftbase,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define MOTORBOUND(X) (X)*(100/127)
#define DESENSITIZE(X) ((abs(X) <10)? 0: (X))

void movebase(int x, int y)
{
	x = DESENSITIZE(x);
	y = DESENSITIZE (y);
	//int rightPower = MOTORBOUND(DESENSITIZE(joystick.joy1_x1 + joystick.joy1_y1));
	motor[rightbase] = MOTORBOUND(DESENSITIZE(x) + DESENSITIZE(y));
	motor[leftbase] = MOTORBOUND(DESENSITIZE(y) - DESENSITIZE(x));
}

void lift()
{
	motor[elevator] = MOTORBOUND(DESENSITIZE(joystick.joy2_y1));
}

void para()
{
	motor[arm] = MOTORBOUND(DESENSITIZE(joystick.joy2_y2));
}

task main()
{

	waitForStart();
	while(1==1)
	{
		movebase(joystick.joy1_x1, joystick.joy1_y1);
		lift();
		para();
	}
}
