#pragma config(Sensor, S4,     IRseek,         sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"

//start code

int getIntensity(){
	int acS1, acS2, acS3, acS4, acS5 = 0;
	int maxSig = 0;
	if(HTIRS2readAllACStrength(IRseek, acS1, acS2, acS3, acS4, acS5)){
		maxSig = (acS1 > acS2) ? acS1 : acS2;
		maxSig = (maxSig > acS3) ? maxSig : acS3;
		maxSig = (maxSig > acS4) ? maxSig : acS4;
		maxSig = (maxSig > acS5) ? maxSig : acS5; //sets maxSig to maximum intensity
	}
	return maxSig; //makes getIntensity() return the highest intensity
}

//end
task main()
{
	int distance = 0;
	while(true){
		distance = getIntensity();
	}
}
