#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     color,          sensorLightActive)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     IRseek,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S3_C1_1,     LeftBase,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     RightBase,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_2,     Elev,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S3_C3_2,    servo2,               BadType)
#pragma config(Servo,  srvo_S3_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define TIME_INTERVAL  10

#define BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_WHEEL(x) ((abs(x) >= 10)? x: 0)

void main_wheel( int joy_x, int joy_y )
{
	 float k=1;
	 int drivePower, turnPower;

   joy_y = k*joy_y;
   drivePower = DEADBAND_WHEEL(joy_x);
   turnPower  = DEADBAND_WHEEL(joy_y);

   motor[LeftBase] = BOUND_WHEEL(drivePower + turnPower);
   motor[RightBase] = BOUND_WHEEL(drivePower - turnPower);
}

#define BOUND_WHEEL_2(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_WHEEL_2(x) ((abs(x) >= 10)? x: 0)

void main_wheel_2( int joy_m, int joy_n )
{
	 float k=6;
	 int drivePower, turnPower;

   joy_n = joy_n/k;
   joy_m = joy_m/k;
   drivePower = DEADBAND_WHEEL(joy_m);
   turnPower  = DEADBAND_WHEEL(joy_n);

   motor[LeftBase] = BOUND_WHEEL(drivePower + turnPower);
   motor[RightBase] = BOUND_WHEEL(drivePower - turnPower);

}

   //-----  ARM LIFT ----
#define BOUND_ARM(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //Makes sure that the joystick is between -100 and 100 (limits big)
#define DEADBAND_ARM(x) ((abs(x) >= 6)? x: 0) //limits sensitivity (small)
void lift(int joy_k){
	int k = 3;
	int drivePower = DEADBAND_ARM(joy_k/k);
	motor[Arm] = BOUND_ARM(drivePower);
}

//----- ARM ELEV ----
#define BOUND_ELEV(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_ELEV(x) ((abs(x) >= 10)? x: 0)
#define MOTION_LIMIT  11000
void elevMove(int joy_k)
{
	int k = -1;
	int drivePower = DEADBAND_ELEV(joy_k/k);

  if ( drivePower < 0 && nMotorEncoder[Elev] >= MOTION_LIMIT ) //top limit
		motor[Elev] = 0;
  else
  if (drivePower > 0 && nMotorEncoder[Elev] <= 0) //bottom limit
  	motor[Elev] = 0;
	else
		motor[Elev] = BOUND_ELEV(drivePower);
}

void elevMoveFree(int joy_k)
{
	int k;
	k = -1;
	int drivePower = DEADBAND_ELEV(joy_k);
	drivePower = drivePower * k;
	motor[Elev] = BOUND_ELEV(drivePower);
}

/*
#define MOTION_STEP		360*2
void elevUpDown( int btn_n, int btn_m )
{
	if ( nMotorRunState[Elev] != runStateIdle  )
		return;

	if ( btn_n == 1 )
	{
		motor[Elev] = 0;
		nMotorEncoderTarget[Elev]=MOTION_STEP;
		motor[Elev] = 10;
	}
  else
  if ( btn_m == 1 )
	{
		motor[Elev] = 0;
		nMotorEncoderTarget[Elev]=-MOTION_STEP;
		motor[Elev] = -10;
	}
} */

void resetElevEncoder(int btn_k)
{
	if ( btn_k == 1 )
  {
  	nxtDisplayTextLine(2, "Elev:%d",nMotorEncoder[Elev]);
		nMotorEncoder[Elev] = 0;
		motor[Elev] = 0; //stop it
	}
}


//----- ARM SERVO -----
#define BOUND_SERVO(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_SERVO(x) ((abs(x) >= 50)? x: 0)
int servo_angle = 240;
void servoAngle(int btn_x)
{
	int angle;
	angle = servo_angle;
	if(btn_x == 1)
	{
		servo[servo1] = angle;
	}
}
#define BOUND_SERVO_1(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_SERVO_1(x) ((abs(x) >= 50)? x: 0)
int servo_initial = 170;
void servoInitial(int btn_y)
{
	int initial;
	initial = servo_initial;
	if (btn_y == 1)
	{
		servo[servo1] = initial;
	}
}

//-------Motor Encoder thing----
void displayMessage(int btn_k)
{
	if ( btn_k == 1 )
		nxtDisplayTextLine(2, "Elev:%d",nMotorEncoder[Elev]);
}

void initializeRobot()
{
	nMotorEncoder[Elev] = 0;
}

task main()
{
	initializeRobot();
	while(true)
	{
		getJoystickSettings(joystick);

		main_wheel(joystick.joy1_x1, joystick.joy1_y1);

		if ( joy1Btn(7)==1 )
			main_wheel_2(joystick.joy1_x2, joystick.joy1_y2);

		lift(joystick.joy2_y1);

		if ( joy2Btn(8)==1 )
			elevMoveFree(joystick.joy2_y2);
	  else
			elevMove(joystick.joy2_y2);

		resetElevEncoder(joy2Btn(3));

		/*
		if ( joy2Btn(7)==1 && joy2Btn(8)==1 )
			motor[Elev] = 0;
		*/

		servoInitial(joy2Btn(2));
		servoAngle (joy2Btn(4));
		displayMessage(joy2Btn(1));

		wait1Msec(TIME_INTERVAL);
	}

}
