#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define TIME_INTERVAL  10


#define SINGLE_BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!//
#define SINGLE_DEADBAND_WHEEL(x) ((abs(x) >= 10)? x: 0)

void single_main_wheel( int joy_x, int joy_y )
{
	 float k=1;
	 int drivePower, turnPower;

   joy_y = k*joy_y;
   drivePower = SINGLE_DEADBAND_WHEEL(joy_x);
   turnPower  = SINGLE_DEADBAND_WHEEL(joy_y);

   motor[motorLeft] = SINGLE_BOUND_WHEEL(drivePower + turnPower);
   motor[motorRight] = SINGLE_BOUND_WHEEL(drivePower - turnPower);
}



/*
//#define BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!//
//#define DEADBAND_WHEEL(x) ((abs(x) >= 25)? x: 0)

void main_wheel( int joy_x, int joy_y )
{
	 float k=4;
	 int drivePower, turnPower;

   joy_y = k*joy_y;
   drivePower = DEADBAND_WHEEL(joy_x);
   turnPower  = DEADBAND_WHEEL(joy_y);

   motor[LeftBase] = BOUND_WHEEL(drivePower + turnPower);
   motor[RightBase] = BOUND_WHEEL(drivePower - turnPower);
}
*/



//-----  ARM LIFT ----
#define BOUND_ARM(x) (((x) > 50)? 50: ((x) < -50)? -50: (x)) //Makes sure that the joystick is between -100 and 100 (limits big)
#define DEADBAND_ARM(x) ((abs(x) >= 4)? x: 0) //limits sensitivity (small)

void lift(int joy_k)
{
	float k = 1 ;
	int drivePower = DEADBAND_ARM(joy_k/k);
	motor[arm] = BOUND_ARM(drivePower);
}


//----- WINCH ----
#define BOUND_WINCH(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_WINCH(x) ((abs(x) >= 10)? x: 0)

void winchmove(int joy_k)
{
	int k;
	k = 1;
	int drivePower = DEADBAND_WINCH(joy_k);
	drivePower = drivePower * k;
	motor[winch] = BOUND_WINCH(drivePower);
}



//----- ARM SERVO -----

#define BOUND_SERVO(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_SERVO(x) ((abs(x) >= 50)? x: 0)
int servo_flat = 0;
void servoFlat(int btn_x)
{
	int flat;
	int k;
	flat = servo_flat;
	k = -1;
	if(btn_x == 1)
	{
		servo[servo1] = flat;
		servo[servo2] = k * flat;
	}
}



#define BOUND_SERVO_1(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_SERVO_1(x) ((abs(x) >= 50)? x: 0)
int servo_drop = 138;
void servoDrop(int btn_y)
{
	int drop;
	int k;
	drop = servo_drop;
	k = -1;
	if (btn_y == 1)
	{
		servo[servo1] = drop;
		servo[servo2] = k * drop;
	}
}



#define BOUND_SERVO_2(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_SERVO_2(x) ((abs(x) >= 50)? x: 0)
int servo_raise = 250;
void servoRaise(int btn_z)
{
	int raise;
	int k;
	raise = servo_raise;
	k = -1;
	if (btn_z == 1)
	{
		servo[servo1] = raise;
		servo[servo2] = k * raise;
	}
}




#define BOUND_SERVO_3(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*//
#define DEADBAND_SERVO_3(x) ((abs(x) >= 50)? x: 0)
int servo_angledown = -10;
void servoAngleDown(int btn_w)
{
	int angledown;
	int k;
	angledown = servo_angledown;
	k = -1;
	if(btn_w == 1)
	{
		servo[servo1] = angledown;
		servo[servo2] = k * angledown;
	}
}


task main()
{
	//initializeRobot();
	while(true)
	{

		getJoystickSettings(joystick);


		single_main_wheel(joystick.joy1_x2, joystick.joy1_y2);
		//main_wheel(joystick.joy1_x1, joystick.joy1_y1);



		lift(joystick.joy2_y1);


		winchmove(joystick.joy2_y2);


		servoFlat(joy2Btn(1));
		servoDrop(joy2Btn(2));
		servoRaise(joy2Btn(4));
		servoAngleDown(joy2Btn(3));



		wait1Msec(TIME_INTERVAL);
	}
}
