#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftBase,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightBase,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Elev,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               BadType)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define MOTOR_THRESHOLD 50
#define MOTORVAL(X) ((X>MOTOR_THRESHOLD)? 100: ((X<-MOTOR_THRESHOLD)? -100: 0))
#define MOTOR2VAL(X) ((X>MOTOR_THRESHOLD)? 60: ((X<-MOTOR_THRESHOLD)? -10: 10))
#define DEADBAND(x) ((abs(x) >= 10)? x: 0)

#define TIME_INTERVAL 100
#define INITIAL_SERVO_VALUE 172 //check for default value
#define SERVO_CHANGE_RATE 2

int servostep = 41;
//float k = 100/127;

void main_wheel(int xVal, int yVal){
	motor[RightBase] = (MOTORVAL(yVal - xVal));
	motor[LeftBase] = (MOTORVAL(yVal + xVal));
}

void lift(int speed){
	motor[Arm] = MOTOR2VAL(speed);
	//int speed2 = speed*k;
	//motor[Arm] = DEADBAND(speed2);
}

void para (int upspeed){
	motor[Elev] = MOTORVAL(upspeed);
}

void servoSwitch(int up, int down){
	if(up == 1){
		servo[servo1] = INITIAL_SERVO_VALUE;
	}
	else if (down == 1){
		servo[servo1] = INITIAL_SERVO_VALUE + servostep;
	}
}

task main()
{

	//initializeRobot();
	while(true){
		getJoystickSettings(joystick);
		servoChangeRate[servo1] = SERVO_CHANGE_RATE;

		main_wheel(joystick.joy1_x1, joystick.joy1_y1);
		lift(joystick.joy2_y1);
		para(joystick.joy2_y2);
		servoSwitch(joy1Btn(2), joy1Btn(4));
	}

}
