#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void patpat_cine()
{
	motor[motorRight] = 4;
 	motor[motorLeft] = -4;
  wait1Msec(300000);
}

void wait()
{
	motor[motorRight] = 0;
	motor[motorLeft] = 0;
	wait1Msec(60000);
}

task main()
{
 patpat_cine();

 wait();

 patpat_cine();

 wait();

 patpat_cine();

 wait();

 patpat_cine();

 wait();

 patpat_cine();

 wait();

 patpat_cine();

 wait();
}
