#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     bob,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     joe,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     kevin,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     swag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     jessie,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     jocelyn,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    dog,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    mice,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    grass,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    roll,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    suchfun,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    wow,                  tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define SINGLE_BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!//
#define SINGLE_DEADBAND_WHEEL(x) ((abs(x) >= 10)? x: 0)

void single_main_wheel(int joy_x, int joy_y)
{
	float k=.77;
	int drivepower, turnpower;

	drivepower = - SINGLE_DEADBAND_WHEEL(k*joy_x);














task main()
{

motor [kevin] = 80;
motor [swag] = 80;
wait1Msec(2300);

motor [kevin] = 80;
motor [swag] = -80;
wait1Msec(1200);

motor [kevin] = -80;
motor [swag] = -80;
wait1Msec(500);

	while(true)
	{
		motor [kevin] = 40;
		motor [swag] = -40;
		motor [bob] = 20;
		wait1Msec(650);

		motor [kevin] = 40;
		motor [swag] = -40;
		motor [bob] = -20;
		wait1Msec(650);
	}
}
