	#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
#pragma config(SrvoPosition,  Position02,            128, 128, 128, 128, 128, 128, 128, 128)
#pragma config(SrvoPosition,  Position01,            112,  38, 128, 128, 128, 128, 128, 128)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define TIME_INTERVAL 5

#define SINGLE_BOUND_WHEEL(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!//
#define SINGLE_DEADBAND_WHEEL(x) ((abs(x) >= 10)? x: 0)

void patpat(int left_in, int right_in)
{
	float k = .4;
	int rightPower, leftPower;

	leftPower = SINGLE_DEADBAND_WHEEL(k * left_in);
	rightPower = SINGLE_DEADBAND_WHEEL(k * right_in);

	motor[motorLeft] = SINGLE_BOUND_WHEEL(leftPower);
  motor[motorRight] = SINGLE_BOUND_WHEEL(rightPower);
}

task main()
{
	while(true)
	{

	getJoystickSettings(joystick);

	patpat(joystick.joy1_y1, joystick.joy1_y2);
	}
}
