#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     color,          sensorLightActive)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IRseek,         sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S3_C1_1,     LeftBase,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C2_1,     RightBase,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C2_2,     Elev,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S3_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//THIS SHOULD MAKE IT TURN LEFT. IF IT DOESNT WORK, WE'RE F*CKED

//Run each step, one at a time by commenting and uncommenting the steps.

task main()
{
	/*//step 1
	motor[LeftBase] = 20;
	motor[RightBase] = 80;
	wait1Msec(4000);
	motor[LeftBase] = 0;
	motor[RightBase] = 0;
	wait1Msec(1000);
	*/

	//step 2

	int IRZone = SensorValue[IRseek];
	int val = IRZone - 5;
	int k = 12; //need to adjust for turning, is turning constant*****ADJUST

	while(true)
	{ //should follow IR beacon
		motor[LeftBase] = 50 + (val*k);
		motor[RightBase] = 50 - (val*k);
	}
	wait1Msec(50);
	motor[LeftBase] = 0;
	motor[RightBase] = 0;

}
