#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Motor,  mtr_S1_C1_1,     LeftBase,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightBase,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Elev,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define K 100/127

#define MOTOR_THRESHOLD 50
#define MOTORVAL(X) ((X>MOTOR_THRESHOLD)? 100: ((X<-MOTOR_THRESHOLD)? -100: 0))

#include "JoystickDriver.c"

task main()
{
	nMotorEncoder[Elev] = 0;
	getJoystickSettings(joystick);
	while(true){

		if(joystick.joy1_y1 > 50 && nMotorEncoder[Elev] <= 1440){
			motor[Elev] = 100;
		}
		else if(joystick.joy1_y1 < -50 && nMotorEncoder[Elev] > 0){
			motor[Elev] = -100;
		}
		else{
			motor[Elev] = 0;
		}
}
	wait1Msec(1000);

}
