#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    excavator,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#define TIME_INTERVAL	5

/*Servo value of 0 = Full Power/Speed Reverse
Servo value of 127 = Stop
Servo value of 256 = Full Power/Speed Forward*/
#define SERVO_IN			0
#define SERVO_OUT			180
#define SERVO_STOP		128

#define SERVO_CHANGE_RATE		10

#define BOUND_SERVOIN(x) (((x) > 100)? 100: ((x) < -100)? -100: (x)) //*!!Makes sure that the joystick is between -100 and 100 !!*/
#define DEADBAND_SERVOIN(x) ((abs(x) >= 50)? x: 0)

void claw_servo_in (int btn1) {
	//nxtDisplayTextLine(1, "Claw Servo In");
	if (btn1) {
		nxtDisplayTextLine(1, "IN");
		servo[excavator] = SERVO_IN;
	}
}

void claw_servo_out (int btn2) {
	if (btn2) {
		nxtDisplayTextLine(1, "OUT");
		servo[excavator] = SERVO_OUT;
	}
}

void claw_servo_stop (int btn_x) {
	if (btn_x) {
		servo[excavator] = SERVO_STOP;
	}
}

void initRobot() {
	servoChangeRate[excavator] = SERVO_CHANGE_RATE;
}

task main() {
	initRobot();
	while(true) {
		getJoystickSettings(joystick);

		/*    TEST SERVO
		servo[excavator] = SERVO_IN;
		wait1Msec(1000);
		servo[excavator] = SERVO_OUT;
		wait1Msec(1000);
		*/

		//writeDebugStreamLine("%d", joy1Btn(3));
		//writeDebugStreamLine("1");
		claw_servo_in(joy1Btn(4));
		claw_servo_out(joy1Btn(2));
		//claw_servo_stop(joy1Btn(3));

		wait1Msec(TIME_INTERVAL);
	}
}
