#pragma config(Sensor, S1,     gyro,           sensorI2CHiTechnicGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define gyroOffset 594

long gyroVal;
float direction;
long deadband(long x)
{
	if (x > -2 && x < 2)
		return 0;
	else
		return x;
}
task main()
{
	direction = 90;

	while (true)
	{
	wait1Msec(5);
	gyroVal = deadband(SensorValue(gyro)-gyroOffset);
	direction = direction - ((float)gyroVal/190);
	while (direction >= 360)
		direction = direction - 360;
	while (direction < 0)
		direction = direction + 360;
	writeDebugStreamLine("%f", direction);
	}
}
