#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTServo)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     FRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Brush,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     FLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BLWheelMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     LLinear,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     Shooter,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     RLinear,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     BRWheelMotor,  tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    LTalon,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    gate,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    BRHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    FLHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    BLHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    FRHoodLeg,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_1,    RTalon,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		writeDebugStreamLine("%d", ServoValue[LTalon]);
		wait1Msec(300);
	}
}
