#pragma config(Sensor, S1,     ultrasonic,     sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long deadband(long x)
{
	if (x > -2 && x < 2)
		return 0;
	else
		return x;
}
task main()
{
	while (true)
	{
	wait1Msec(10);
	nxtDisplayBigTextLine(1, "%d", SensorValue[ultrasonic]);
	//writeDebugStreamLine("%d", SensorValue[ultrasonic]);
	}
}
